config/routes.rb
Rails.application.routes.draw do

  resources :promos do
    resources :classrooms
  end

  resources :classrooms do
    resources :students
  end



  devise_for :users, controllers: { registrations: "users/registrations"}
root to:'promos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  #RELATIONS
  belongs_to :promo
  has_many :students, dependent: :destroy


  #SLUG
  extend FriendlyId
    friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
      title_changed?
  end

end

app/models/promo.rb
class Promo < ApplicationRecord
  belongs_to :user

 #slug
  extend FriendlyId
    friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
      title_changed?
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :classroom

  #slug
  extend FriendlyId
    friendly_id :username, use: :slugged

  def should_generate_new_friendly_id?
      username_changed?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #RELATIONS
  has_many :promos

 #slug
  extend FriendlyId
    friendly_id :username, use: :slugged

  def should_generate_new_friendly_id?
      username_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_promo
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  def create
    @classroom = @promo.classrooms.build(classroom_params)

    if @classroom.save
      redirect_to promo_classroom_path(@promo, @classroom), notice: 'Classroom was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /classrooms/1
  def update
      if @classroom.update(classroom_params)
      redirect_to promo_classroom_path(@promo, @classroom), notice: 'Classroom was successfully updated.'
    else
      render :edit
    end

  end

  # DELETE /classrooms/1
  def destroy
    @classroom.destroy
    redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_classroom
      @classroom = @promo.classrooms.friendly.find(params[:id])
    end
    def set_promo
      @promo = Promo.friendly.find(params[:promo_id])
    end
    # Only allow a trusted parameter "white list" through.
    def classroom_params
      params.require(:classroom).permit(:title, :slug, :promo_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all#.order(created_at: :DESC)
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo             = current_user.promos.build(promo_params)
    @promo.school_code = current_user.school_code

    if @promo.save
      redirect_to @promo, notice: 'Promo was successfully created.'
    else
     render :new
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    if @promo.update(promo_params)
      redirect_to @promo, notice: 'Promo was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    redirect_to promos_url, notice: 'Promo was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def promo_params
      params.require(:promo).permit(:title, :school_code, :slug, :user_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  def index
    @students = Student.all
  end

  # GET /students/1
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student, notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /students/1
  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    redirect_to students_url, notice: 'Student was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.require(:student).permit(:username, :matricule, :matricule_school, :contact_student_1, :contact_student_2, :contact_parent_1, :contact_parent_2, :slug, :classroom_id)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]


  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :contact, :post, :school_code,
                                                        :city, :role, :school_name, :slug])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :username, :contact, :post, :school_code,
                                                        :city, :role, :school_name, :slug])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "LNCLASS"
    if @title.nil?
      base_title
    else
      "#{@title} - #{base_title}"
    end
  end


  #User sign in ou Sign up Form anywhere

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classrooms/_form.html.erb
<%= form_with(model: [@promo, @classroom], local: true) do |form| %>
  <% if classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
        <% classroom.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"Crée la Classe:" %>
    <%= form.text_field :title , placeholder: "Nom de la Classe"  %>
  </div>


  <div class="actions">
    <%= form.submit "Ajoute la Classe", class: 'btn btn-primary' %>
    <%= link_to 'Annuler', @promo, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h3>
  Editer Classroom
  <%= link_to 'View', promo_classroom_path(@promo, @classroom), class: 'btn btn-outline-primary' %>
</h3>

<%= render 'form', promo: @promo,classroom: @classroom %>

app/views/classrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classrooms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Promo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.title %></td>
        <td><%= classroom.slug %></td>
        <td><%= classroom.promo_id %></td>
        <td><%= link_to 'Show', classroom %></td>
        <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
        <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/new.html.erb
<div class="mt-20 content-end">
  <h3 class="font-bold mb-2">Ajoutez les Classes</h3>
  <%= render 'form', promo: @promo, classroom: @classroom %>
</div>

app/views/classrooms/show.html.erb
<h3 class='d-flex justify-content-between mb-5 mt-12'>
  <%= link_to 'Retour', promo_classroom_path(@promo, @classroom), class: 'btn btn-secondary mb-3' %>
    <div>
      <%= link_to  edit_promo_classroom_path(@promo, @classroom), class: 'btn btn-outline-primary font-bold' do %>
           Classe <%= @classroom.title %>
      <% end %>
    </div>

  <div class="card d-flex justify-content-between m-2">
  <%= link_to classroom_students_path(@classroom), class:"bg-white font-bold btn btn-outline-primary" do %>
   <i class="fa fa-cercle-plus"></i> Inscription
  <% end %>

  </div>

</h3>

app/views/home/_logged_up.html.erb
<link href="https://raw.githubusercontent.com/daneden/animate.css/master/animate.css" rel="stylesheet">

<div id="myCarousel" class="carousel slide carousel-fade mt-6 -m-2" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="mask flex-center">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-7 col-12 order-md-1 order-2">
              <h4>Present your <br>
                awesome product</h4>
              <p>Lorem ipsum dolor sit amet. Reprehenderit, qui blanditiis quidem rerum <br>
                necessitatibus praesentium voluptatum deleniti atque corrupti.</p>
              <%= link_to "COMPTE OFFICIEL", new_user_registration_path %> </div>
            <div class="col-md-5 col-12 order-md-2 order-1"><img src="https://i.imgur.com/NKvkfTT.png" class="mx-auto" alt="slide"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="mask flex-center">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-7 col-12 order-md-1 order-2">
              <h4>Present your <br>
                awesome product</h4>
              <p>Lorem ipsum dolor sit amet. Reprehenderit, qui blanditiis quidem rerum <br>
                necessitatibus praesentium voluptatum deleniti atque corrupti.</p>
              <%= link_to "COMPTE OFFICIEL", new_user_registration_path %> </div>
            <div class="col-md-5 col-12 order-md-2 order-1"><img src="https://i.imgur.com/duWgXRs.png" class="mx-auto" alt="slide"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="mask flex-center">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-7 col-12 order-md-1 order-2">
              <h4>Present your <br>
                awesome product</h4>
              <p>Lorem ipsum dolor sit amet. Reprehenderit, qui blanditiis quidem rerum <br>
                necessitatibus praesentium voluptatum deleniti atque corrupti.</p>
              <%= link_to "COMPTE OFFICIEL", new_user_registration_path %> </div>
            <div class="col-md-5 col-12 order-md-2 order-1"><img src="https://i.imgur.com/DGkR4OQ.png" class="mx-auto" alt="slide"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div>
<!--slide end-->

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= render "logged_in" %>
  <% else %>
  <%= render "logged_up" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render 'layouts/partials/header_links' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class=" bg-gray-200">
    <%= render "shared/nav/navbar" %>
    <div class="pt-16 md:m-2">
      <%= render 'layouts/partials/notices' %>
      <%= yield %>
    </div>
    <%= render 'layouts/partials/footer_links' %>
  </body>
</html>

app/views/layouts/partials/_footer_links.html.erb
<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

app/views/layouts/partials/_header_links.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= stylesheet_pack_tag    'application' %>
<%= javascript_pack_tag 'application' %>
<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<script src="https://kit.fontawesome.com/2ec2a30cc1.js" crossorigin="anonymous"></script>

app/views/layouts/partials/_notices.html.erb
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/promos/_form.html.erb
<%= simple_form_for(@promo) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/promos/edit.html.erb
<%= link_to 'Back', promos_path %>


<h3>
  Editer la promotion
  <%= link_to 'View', @promo, class: 'btn btn-outline-primary' %>
</h3>

<%= render 'form', promo: @promo %>

app/views/promos/index.html.erb
<% content_for @title= "Accueil" %>

<div class="card mt-40">

</div>
<h3 class='d-flex justify-content-between m-2'>
  <span>Promotions</span>
  <%= link_to  new_promo_path, class: 'btn btn-outline-primary' do %>
  <i class="fa fa-plus-circle" aria-hidden="true"></i> Promotion
  <% end %>
</h3>

<div class="row">
  <% @promos.each do |promo| %>
    <div class="col-md-4">
        <div class="card border-dark mb-2">
          <div class="card-body">
            <h5 class='card-title d-flex justify-content-between'>
              <%= link_to promo do %>
                <button type="button" class="btn bg-gray-300 rounded-r rounded-l">
                  Promotion <span class="badge badge-light"><%= promo.title %></span>
                </button>
              <% end %>
              <div class="dropdown">
                <button class="btn btn-light" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-h"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <%= link_to 'Edit', edit_promo_path(promo), class: 'dropdown-item' %>
                  <%= link_to 'Delete', promo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>
                </div>
              </div>
            </h5>
            <div class="stats mb-4">
              <p class='classroom-count'><%= promo.classrooms.count %> classes</p>

            </div>
            <%= link_to  promo, class: 'btn btn-outline-info' do %>
              <i class="fa fa-plus-circle" aria-hidden="true"></i> Voir Plus
            <% end %>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/promos/new.html.erb
<h1>New Promo</h1>

<%= render 'form', promo: @promo %>

<%= link_to 'Back', promos_path %>

app/views/promos/show.html.erb
<div class="card mt-32"></div>
<h3 class='mb-4 font-bold'>
  <%= link_to 'Retour', promos_path, class: 'btn btn-secondary mb-3' %>
  <%= link_to  edit_promo_path(@promo), class: 'btn btn-outline-primary'  do %>
    Classe <%= @promo.title %>
  <% end %>
</h3>



<h5 class='d-flex justify-content-between m-4'>
  <span>Les classes</span>
  <%= link_to new_promo_classroom_path(@promo), class: 'btn btn-outline-primary' do %>
    <i class="fa fa-plus-circle" aria-hidden="true"></i> Classe
  <% end %>

</h5>

<div class="row">
  <% @promo.classrooms.each do |classroom| %>
    <div class="col-md-4">
        <div class="card border-dark mb-2">
          <div class="card-body">
            <h5 class='card-title d-flex justify-content-between'>
              <%= link_to promo_classroom_path(@promo, classroom) do %>
                <button type="button" class="btn bg-gray-300 rounded-r rounded-l">
                  <span class="badge badge-light">Classe <%= classroom.title %></span>
                </button>
              <% end %>
              <div class="dropdown">
                <button class="btn btn-light" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-h"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <%= link_to 'Editer', edit_promo_classroom_path(@promo, classroom), class: 'dropdown-item' %>
                  <%= link_to 'Delete', promo_classroom_path(@promo, classroom), method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>
                </div>
              </div>
            </h5>

            <%= link_to  promo_classroom_path(@promo, classroom), class: 'btn btn-outline-info' do %>
              <i class="fa fa-plus-circle" aria-hidden="true"></i> Voir Plus
            <% end %>
          </div>
        </div>
    </div>
  <% end %>

app/views/shared/nav/_navbar.html.erb
<nav class="navbar navbar-expand-md fixed-top bg-white">
  <a class="navbar-brand font-bold m-links logo ml-32" href="/">LNCLASS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if user_signed_in? %>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link font-semibold m-links" href="/">
          <i class="fas fa-house-user"></i> Accueil <span class="sr-only">(current)</span></a>
      </li>

    </ul>
    <ul class="mt-md-0">
      <li class="nav-item active">
        <%= link_to edit_user_registration_path, class: "m-links nav-link font-bold" do %>
         <i class="rounded-full h-6 w-6 flex items-center justify-center bg-gray-400">V</i>
        <% end %>
      </li>
    </ul>
     <ul class="mt-md-0">
      <li class="nav-item active">
        <%= link_to root_path, class: "m-links nav-link font-bold" do %>
          <i class="fas fa-user-circle"></i> Assistant
        <% end %>
      </li>
    </ul>

      <ul>
      <li class="nav-item active">
        <%= link_to destroy_user_session_path, method: :delete, class: "m-links nav-link font-bold mr-32" do %>
          <i class="fa fa-power-off" aria-hidden="true"></i> Déconnexion
        <% end %>
      </li>
    </ul>
  </div>
  <% end %>
</nav>
<p class="bg-blue-600 h-1 -mt-4 -m-6"></p>

app/views/students/_form.html.erb
<%= simple_form_for(model: [classroom, student], local: true) do |f| %>

  <div class="form-inputs">
    <%= f.input :username %>
    <%= f.input :matricule %>
    <%= f.input :matricule_school %>
    <%= f.input :contact_student_1 %>
    <%= f.input :contact_student_2 %>
    <%= f.input :contact_parent_1 %>
    <%= f.input :contact_parent_2 %>
    <%= f.input :slug %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Matricule</th>
      <th>Matricule school</th>
      <th>Contact student 1</th>
      <th>Contact student 2</th>
      <th>Contact parent 1</th>
      <th>Contact parent 2</th>
      <th>Slug</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.username %></td>
        <td><%= student.matricule %></td>
        <td><%= student.matricule_school %></td>
        <td><%= student.contact_student_1 %></td>
        <td><%= student.contact_student_2 %></td>
        <td><%= student.contact_parent_1 %></td>
        <td><%= student.contact_parent_2 %></td>
        <td><%= student.slug %></td>
        <td><%= student.classroom_id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to  new_classroom_student_path , class: " btn btn-outline-primary font-bold bbg-white" do%>
  New Student
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @student.username %>
</p>

<p>
  <strong>Matricule:</strong>
  <%= @student.matricule %>
</p>

<p>
  <strong>Matricule school:</strong>
  <%= @student.matricule_school %>
</p>

<p>
  <strong>Contact student 1:</strong>
  <%= @student.contact_student_1 %>
</p>

<p>
  <strong>Contact student 2:</strong>
  <%= @student.contact_student_2 %>
</p>

<p>
  <strong>Contact parent 1:</strong>
  <%= @student.contact_parent_1 %>
</p>

<p>
  <strong>Contact parent 2:</strong>
  <%= @student.contact_parent_2 %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @student.slug %>
</p>

<p>
  <strong>Classroom:</strong>
  <%= @student.classroom_id %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>